Repository boostcampwm-2024/refactor-web33-Nocta, pull requests merged in 2025-02, with the labels that each got.

#23 Hotfix/Docker 컨테이너에서 bcrypt 모듈을 찾지 못하는 문제 수정
  .github/workflows/deploy.yml
  client/Dockerfile
  pnpm-lock.yaml
  server/package.json
  server/src/auth/auth.service.ts
  server/src/auth/test/auth.service.spec.ts
Labels: Bug

#26 Feature/#022 ai 문서작성 기능 구현
  .github/workflows/deploy.yml
  client/Dockerfile
  client/src/apis/ai.ts
  client/src/features/ai/AIModal.tsx
  client/src/features/editor/utils/domSyncUtils.ts
  pnpm-lock.yaml
  server/package.json
  server/src/ai/ai.controller.ts
  server/src/ai/ai.module.ts
  server/src/ai/ai.service.ts
  server/src/app.module.ts
Labels: FE, BE

#27 Feature/#025 ai 문서기능 완성도 개선
  client/src/components/Toast/Toast.style.ts
  client/src/components/Toast/Toast.tsx
  client/src/features/ai/AIButton.tsx
  client/src/features/ai/AIModal.style.ts
  client/src/features/ai/AIModal.tsx
  client/src/features/workSpace/components/OnboardingOverlay.style.ts
  client/src/features/workSpace/components/OnboardingOverlay.tsx
Labels: FE

#28 Hotfix/배포 단계에서 CLOVA Studio API 관련 환경 변수가 적용되도록 수정
  .github/workflows/deploy.yml
  docker-compose.yml
Labels: Bug, Build

#30 Feature/#029 리스트 가상화 순서이동 버그
  client/src/features/editor/components/block/Block.tsx
  client/src/features/editor/utils/domSyncUtils.ts
Labels: Bug

#31 Refactor/FE UX 최적화
  client/src/features/ai/AIModal.style.ts
  client/src/features/ai/AIModal.tsx
  client/src/features/workSpace/components/OnboardingOverlay.tsx
Labels: Refactor, FE

#33 Feature/#032 ai 응답 ux 개선
  client/src/features/workSpace/hooks/usePagesManage.ts
  server/src/ai/ai.controller.ts
  server/src/ai/ai.service.ts
  server/src/workspace/workspace.service.ts
Labels: Refactor, FE, BE

#35 Feature/#34 open ai 변경
  .github/workflows/deploy.yml
  client/src/components/Toast/ToastContainer.style.ts
  docker-compose.yml
  server/src/ai/ai.service.ts
Labels: BE

#40 Hotfix/생성 중인 페이지가 삭제됐을 때 서버가 다운되는 문제 수정
  server/src/ai/ai.service.ts
  server/src/workspace/workspace.service.ts
Labels: Bug
