Repository boostcampwm-2024/refactor-web33-Nocta, pull requests merged in 2025-01, with the labels that each got.

#9 Refactor/#003 playwright 선택자 설정 및 시나리오 작성
  .gitignore
  client/src/components/bottomNavigator/BottomNavigator.tsx
  client/src/components/button/IconButton.tsx
  client/src/components/button/textButton.tsx
  client/src/components/modal/modal.tsx
  client/src/components/sidebar/Sidebar.tsx
  client/src/components/sidebar/components/pageIconButton/PageIconButton.tsx
  client/src/components/sidebar/components/pageIconButton/PageIconModal.tsx
  client/src/components/sidebar/components/pageItem/PageItem.tsx
  client/src/features/auth/AuthButton.tsx
  client/src/features/auth/AuthModal.tsx
  client/src/features/editor/Editor.tsx
  client/src/features/editor/components/IconBlock/IconBlock.tsx
  client/src/features/editor/components/block/Block.tsx
  client/src/features/page/Page.tsx
  client/src/features/page/components/PageControlButton/PageControlButton.tsx
  client/src/features/page/components/PageTitle/PageTitle.tsx
  client/src/features/workSpace/WorkSpace.tsx
  package.json
  playwright.config.ts
  pnpm-lock.yaml
  tests/auth.spec.ts
  tests/markdown.spec.ts
  tests/page.spec.ts
Labels: FE, Test

#10 Refactor/#004 tombstone 처리 추가 1
  @noctaCrdt/__tests__/LinkedList.test.ts
  @noctaCrdt/jest.config.js
  @noctaCrdt/package.json
  @noctaCrdt/src/Crdt.ts
  @noctaCrdt/src/LinkedList.ts
  @noctaCrdt/src/Node.ts
  @noctaCrdt/src/NodeId.ts
  @noctaCrdt/src/Page.ts
  @noctaCrdt/src/WorkSpace.ts
  @noctaCrdt/src/types/Interfaces.ts
  @noctaCrdt/tsconfig.json
  client/src/components/button/IconButton.tsx
  client/src/components/sidebar/Sidebar.tsx
  client/src/components/sidebar/components/menuButton/components/components/WorkspaceSelectItem.tsx
  client/src/components/sidebar/components/pageIconButton/PageIconButton.tsx
  client/src/components/sidebar/components/pageIconButton/PageIconModal.tsx
  client/src/components/sidebar/components/pageItem/PageItem.tsx
  client/src/constants/PageIconButton.config.ts
  client/src/constants/option.ts
  client/src/features/editor/Editor.tsx
  client/src/features/editor/components/ColorOptionModal/BackgroundColorOptionModal.style.ts
  client/src/features/editor/components/ColorOptionModal/BackgroundColorOptionModal.tsx
  client/src/features/editor/components/ColorOptionModal/TextColorOptionModal.style.ts
  client/src/features/editor/components/ColorOptionModal/TextColorOptionModal.tsx
  client/src/features/editor/components/IconBlock/IconBlock.tsx
  client/src/features/editor/components/MenuBlock/MenuBlock.tsx
  client/src/features/editor/components/OptionModal/OptionModal.tsx
  client/src/features/editor/components/TextOptionModal/TextOptionModal.tsx
  client/src/features/editor/components/TypeOptionModal/TypeOptionModal.tsx
  client/src/features/editor/components/block/Block.tsx
  client/src/features/editor/hooks/useBlockDragAndDrop.ts
  client/src/features/editor/hooks/useBlockOperation.ts
  client/src/features/editor/hooks/useBlockOption.ts
  client/src/features/editor/hooks/useCopyAndPaste.ts
  client/src/features/editor/hooks/useEditorOperation.ts
  client/src/features/editor/hooks/useMarkdownGrammer.ts
  client/src/features/editor/hooks/useTextOptions.ts
  client/src/features/editor/utils/domSyncUtils.ts
  client/src/features/page/Page.tsx
  client/src/features/page/components/PageTitle/PageTitle.tsx
  client/src/features/workSpace/hooks/usePagesManage.ts
  client/src/stores/useSocketStore.ts
  client/src/types/markdown.ts
  client/src/types/page.ts
  client/tsconfig.json
  client/vite.config.ts
  pnpm-lock.yaml
  server/jest.config.ts
  server/package.json
  server/src/workspace/workspace.controller.ts
  server/src/workspace/workspace.gateway.ts
  server/src/workspace/workspace.service.ts
  server/tsconfig.json
  server/webpack.config.js
Labels: Refactor, FE, BE, Test

#11 Hotfix/게스트 워크스페이스에서도 CRDT 가비지 컬렉터가 동작하도록 수정
  server/src/workspace/workspace.service.ts
Labels: Bug, BE

#12 Refactor/#008 블록 렌더링 로직 수정
  client/src/features/editor/components/block/Block.tsx
  client/src/features/editor/utils/domSyncUtils.ts
Labels: Refactor, FE

#18 Refactor/#014 Write Back 캐시 로직을 이벤트 소싱 패턴으로 변경
  @noctaCrdt/src/types/Interfaces.ts
  server/src/workspace/workspace.gateway.ts
  server/src/workspace/workspace.service.ts
Labels: Refactor, BE
