Repository boostcampwm-2024/refactor-web33-Nocta, pull requests merged in 2025-05, with the labels that each got.

#43 Feature/온보딩 및 페이지 ux 개선
  client/package.json
  client/src/App.tsx
  client/src/components/bottomNavigator/BottomNavigator.tsx
  client/src/components/sidebar/Sidebar.tsx
  client/src/features/editor/components/IconBlock/IconBlock.style.ts
  client/src/features/page/hooks/usePage.ts
  client/src/features/workSpace/WorkSpace.tsx
  client/src/features/workSpace/components/OnboardingOverlay.tsx
  client/src/features/workSpace/components/SnapOverlay.style.ts
  client/src/features/workSpace/components/SnapOverlay.tsx
  client/src/features/workSpace/hooks/useWorkspaceInit.ts
  client/src/stores/useSnapStore.ts
  client/src/stores/useSocketStore.ts
  client/src/stores/useUserStore.ts
  client/src/types/page.ts
  pnpm-lock.yaml
Labels: FE

#44 Refactor/useMarkdownGrammer 훅 모듈화
  client/src/features/editor/Editor.tsx
  client/src/features/editor/hooks/markdowngrammer/handlers/arrow.ts
  client/src/features/editor/hooks/markdowngrammer/handlers/backspace.ts
  client/src/features/editor/hooks/markdowngrammer/handlers/delete.ts
  client/src/features/editor/hooks/markdowngrammer/handlers/enter.ts
  client/src/features/editor/hooks/markdowngrammer/handlers/homeend.ts
  client/src/features/editor/hooks/markdowngrammer/handlers/page.ts
  client/src/features/editor/hooks/markdowngrammer/handlers/space.ts
  client/src/features/editor/hooks/markdowngrammer/handlers/tab.ts
  client/src/features/editor/hooks/markdowngrammer/index.ts
  client/src/features/editor/hooks/markdowngrammer/types.ts
  client/src/features/editor/hooks/markdowngrammer/utils/index.ts
Labels: Refactor, FE

#45 CI/배포 과정 최적화
  .github/workflows/deploy.yml
  .github/workflows/lint_and_test.yml
  docker-compose.yml
Labels: Refactor, BE
